from _typeshed import Incomplete

class IOMixin:
    def __init__(self, *args, **kwargs) -> None: ...
    def progress_bar(self, max: int = ...) -> Incomplete: ...
    def ask(self, question, default: Incomplete | None = ...): ...
    def ask_hidden(self, question): ...
    def confirm(self, question, default: bool = ..., true_answer_regex: str = ...): ...
    def choice(self, question, choices, default: Incomplete | None = ...): ...
    def ask_question(self, question): ...
    def write(self, string, flags: int = ...) -> None: ...
    def error(self, string, flags: int = ...) -> None: ...
    def write_line(self, string, flags: int = ...) -> None: ...
    def error_line(self, string, flags: int = ...) -> None: ...
    def overwrite(self, message, size: Incomplete | None = ...) -> None: ...
    def overwrite_error(self, message, size: Incomplete | None = ...) -> None: ...
