name: check-code-style
on: [pull_request]
jobs:
  check-code-style-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check style with black
        run: poetry run black --check shui
      - name: Check style with pylint
        run: poetry run pylint shui --disable=C0301
