name: Check code formatting

on: [pull_request]

jobs:
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        run: pip install poetry

      - name: Install shui dependencies
        run: poetry install

      - name: Check style with black
        run: poetry run black --check shui

      - name: Check style with pylint
        run: poetry run pylint shui --disable=C0301

  check-type-hinting:
    name: Check type hinting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run: pip install poetry

      - name: Install shui dependencies
        run: poetry install

      - name: Check type hinting with mypy
        run: poetry run mypy shui
